# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercalendarevent',
            name='location_city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membercalendarevent',
            name='location_state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membercalendarevent',
            name='location_street_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membercalendarevent',
            name='location_zip_code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
