# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import wagtail.contrib.wagtailroutablepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('member_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventArchive',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', wagtail.contrib.wagtailroutablepage.models.RoutablePageMixin),
        ),
        migrations.AddField(
            model_name='membercalendarevent',
            name='event_end_time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 22, 10, 24, 54, 134403, tzinfo=utc), verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membercalendarevent',
            name='event_start_time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 22, 10, 25, 0, 720133, tzinfo=utc), verbose_name='Start time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membercalendarevent',
            name='event_date',
            field=models.DateField(verbose_name='Event Date'),
        ),
    ]
