# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_calendar', '0006_auto_20170611_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercalendarevent',
            name='asl_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membercalendarevent',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
