# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial_squashed_0003_auto_20170409_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
