# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fundraisingsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisingsnippet',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toplevelpage',
            name='fundraising_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.FundraisingSnippet'),
        ),
    ]
