# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170505_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraisingsnippet',
            old_name='text',
            new_name='embed_code',
        ),
    ]
