# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170505_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingsnippet',
            name='embed_code',
            field=models.TextField(),
        ),
    ]
