# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 21:56
from __future__ import unicode_literals

import common.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20170610_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplevelpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('banner_image', wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('alt_text', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False))))), ('heading', common.blocks.HeaderH1()), ('subheading', common.blocks.Subhead()), ('block_quote', wagtail.wagtailcore.blocks.StructBlock((('quote', wagtail.wagtailcore.blocks.TextBlock(classname='full', max_length=255, required=True)),))), ('call_to_action', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('cta_copy', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('button_title', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('button_link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('button_external_link', wagtail.wagtailcore.blocks.URLBlock(required=False))))), ('cta_button', wagtail.wagtailcore.blocks.StructBlock((('button_copy', wagtail.wagtailcore.blocks.CharBlock(max_length=32)), ('button_link', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('button_external_link', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('tl', 'Left'), ('tr', 'Right'), ('tc', 'Center')]))))), ('captioned_image', wagtail.wagtailcore.blocks.StructBlock((('photo', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('photo_alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')])), ('caption', wagtail.wagtailcore.blocks.CharBlock(max_length=255)), ('caption_alignment', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('tl', 'Left'), ('tr', 'Right'), ('tc', 'Center')]))))))),
        ),
    ]
