# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_socialmediasettings_squashed_0016_auto_20170709_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='logo_wide',
            field=models.ImageField(default='', help_text='Wide-format logo URL. Should be less than 60px high and 600px wide.', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='logo',
            field=models.URLField(help_text='The URL of the logo of your local. Ideally, should be 800x800'),
        ),
    ]
