# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('common', '0015_auto_20170715_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
