# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_seosettings_feed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seosettings',
            name='feed_image',
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='The URL of the logo of your local. Ideally, should be 800x800', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='logo_wide',
            field=models.ForeignKey(blank=True, help_text='Wide-format logo URL. Should be less than 60px high and 600px wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
