# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20170716_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter_screen_name',
            field=models.CharField(blank=True, help_text='Your twitter screenname (with the "@"', max_length=16),
        ),
    ]
