# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_socialmediasettings_twitter_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='address_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='address_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='address_street',
            field=models.CharField(blank=True, help_text='Street address for local (if any)', max_length=255),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
