# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20170802_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplevelpage',
            name='page_date',
            field=models.DateField(default=datetime.date(2017, 9, 21)),
            preserve_default=False,
        ),
    ]
