# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0009_homepage_og_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='share_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Share Image'),
        ),
    ]
