---
- name: Start Supervisor
  service: name=supervisor state=started

- name: Read Supervisord Program
  supervisorctl: name={{ domain }} state=present

- name: Start Supervisord Program
  supervisorctl: name={{ domain }} state=started

- name: Restart Supervisord Program
  supervisorctl: name={{ domain }} state=restarted

- name: Restart Supervisord
  service: name=supervisor state=restarted
